org: ghocevar
app: hackernews-jobs-api
service: hackernews-jobs-api
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-offline
  - serverless-webpack
package:
  individually: true
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
